### ISSUE TITLE
Response time metrics and downtime alerts

### ISSUE THREAD

**Issue by connecteev** [matchai/heads-up#3]
Thanks for this repo @matchai 
I personally would love to use this for these 2 features for monitoring my (External) website. In particular, this would be quite useful:
-  Response time metrics (Uptime %, Cumulative downtime duration)
-  Downtime alerts (Email alert, SMS)

I've starred this repo and I'll be waiting for these features to start using them!

**Comment by matchai** [comment]
This project is not under active development at the moment.
Folks are welcome to fork it and pick up from where I left off! 😄
